Repository academiadev-joinville/projeto-backend-thunderpets, pull requests merged in 2018-10, with the labels that each got.

#1 Configurando projeto e adicionando CircleCI
  .circleci/config.yml
  README.md
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/rest/HelloWorldEndpoint.java
Labels: enhancement, review

#4 Entidades e banco de dados
  .circleci/config.yml
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/enums/Categoria.java
  src/main/java/br/com/academiadev/thunderpets/enums/Idade.java
  src/main/java/br/com/academiadev/thunderpets/enums/Porte.java
  src/main/java/br/com/academiadev/thunderpets/enums/Sexo.java
  src/main/java/br/com/academiadev/thunderpets/enums/Status.java
  src/main/java/br/com/academiadev/thunderpets/enums/TipoPet.java
  src/main/java/br/com/academiadev/thunderpets/model/Endereco.java
  src/main/java/br/com/academiadev/thunderpets/model/Foto.java
  src/main/java/br/com/academiadev/thunderpets/model/Pet.java
  src/main/java/br/com/academiadev/thunderpets/model/Usuario.java
  src/main/resources/application.properties
Labels: enhancement, review

#13 Configuração do Swagger
  README.md
  build.gradle
  src/main/java/br/com/academiadev/thunderpets/config/SwaggerConfig.java
Labels: config, enhancement, review

#14 Crud Pet
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
  src/main/java/br/com/academiadev/thunderpets/repository/PetRepository.java
Labels: enhancement, review

#17 Checkstyle
  .circleci/config.yml
  README.md
  build.gradle
  checkstyle.xml
  src/main/java/br/com/academiadev/thunderpets/ThunderpetsApplication.java
  src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
  src/main/java/br/com/academiadev/thunderpets/model/Pet.java
  src/main/java/br/com/academiadev/thunderpets/repository/PetRepository.java
  suppression.xml
Labels: config, enhancement, review

#18 Checkstyle
  .circleci/config.yml
  README.md
  src/test/java/br/com/academiadev/thunderpets/ThunderpetsApplicationTests.java
Labels: bug, review
